name: Publish Resume

on:
  push:
    branches: # triggers on any push to master
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          target_branch: gh-pages
          build_dir: src
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
